import { chromium } from 'playwright';
const EXE = '/home/piotr/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome';
const b = await chromium.launch({ executablePath: EXE, args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--disable-dev-shm-usage'] });
const p = await b.newPage({ viewport: { width: 1600, height: 900 } });
const errors=[]; p.on('console',m=>{errors.push(m.type()+': '+m.text())}); p.on('pageerror',e=>errors.push('PAGE '+String(e)));
await p.goto('http://localhost:5173/', { waitUntil: 'load', timeout: 60000 });
await p.waitForTimeout(20000);
console.log(await p.evaluate(()=>typeof window.units));
console.log(errors.slice(0,15).join('\n'));
await b.close();
