import { chromium } from 'playwright';
const EXE='/home/piotr/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome';
const b=await chromium.launch({executablePath:EXE,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--disable-dev-shm-usage']});
const p=await b.newPage({viewport:{width:800,height:450}});
const msgs=[];
p.on('console',m=>msgs.push(m.type()+': '+m.text().slice(0,600)));
p.on('pageerror',e=>msgs.push('PAGEERR '+String(e).slice(0,600)));
await p.goto('http://localhost:5173/',{waitUntil:'load',timeout:60000});
await p.waitForTimeout(12000);
console.log(msgs.filter(m=>!/favicon|Failed to load resource|vite/i.test(m)).slice(0,20).join('\n---\n'));
console.log('WATERVIS', await p.evaluate(()=>{const w=window.water; if(!w) return 'no water';
  return JSON.stringify(w.group.children.map(c=>({n:c.type, vis:c.visible, cnt:c.geometry.index?c.geometry.index.count:0, prog: !!c.material.program})));}));
await b.close();
