import { chromium } from 'playwright';
const EXE='/home/piotr/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome';
const b=await chromium.launch({executablePath:EXE,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--disable-dev-shm-usage']});
const p=await b.newPage({viewport:{width:1600,height:900}});
p.on('pageerror',e=>console.log('PAGEERR',String(e)));
p.on('console',m=>{ if(m.type()==='error') console.log('CONSOLE',m.text().slice(0,200)); });
await p.goto('http://localhost:5173/',{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>(window.__frameCount||0)>=6,null,{timeout:200000});
console.log('f0', await p.evaluate(()=>window.__frameCount));
console.log('set', await p.evaluate(()=>{ try{ const u=window.water.u; u.uK0.value.set(0,1,1,1); return 'ok '+JSON.stringify(u.uK0.value); }catch(e){ return 'THREW '+e.message; } }));
await p.waitForTimeout(12000);
console.log('f1', await p.evaluate(()=>window.__frameCount));
await p.waitForTimeout(12000);
console.log('f2', await p.evaluate(()=>window.__frameCount));
await b.close();
