import { chromium } from 'playwright';
const EXE='/home/piotr/.cache/ms-playwright/chromium-1208/chrome-linux64/chrome';
const b=await chromium.launch({executablePath:EXE,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox','--disable-dev-shm-usage']});
const p=await b.newPage({viewport:{width:600,height:340}});
await p.goto('http://localhost:5173/',{waitUntil:'load',timeout:60000});
await p.waitForFunction(()=>window.water&&window.camera,null,{timeout:120000});
await p.evaluate(()=>{ window.water.group.visible=false; window.scene.children.forEach(o=>{if(o.type==='Mesh')o.visible=false;}); });
const n=8+(await p.evaluate(()=>window.__frameCount||0));
await p.waitForFunction(k=>(window.__frameCount||0)>=k,n,{timeout:300000}).catch(()=>{});
await p.screenshot({path:'shots/_zt2.png'});
console.log('ok',await p.evaluate(()=>window.scene.children.map(o=>o.type+o.visible).join(',')));
await b.close();
